// <auto-generated />
using CarRentalAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CarRentalAPI.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandName = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            BrandName = "Honda"
                        },
                        new
                        {
                            Id = 3,
                            BrandName = "Tesla"
                        });
                });

            modelBuilder.Entity("CarRentalAPI.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChasyNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineCapacity")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegistrationNo")
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ModelId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            ChasyNumber = "CH-TOY-001",
                            EngineCapacity = "1800cc",
                            EngineNumber = "EN-TOY-001",
                            FuelType = "Petrol",
                            ModelId = 1,
                            RegistrationNo = "ABC-1234",
                            YearOfManufacture = 2015
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            ChasyNumber = "CH-HON-002",
                            EngineCapacity = "1500cc",
                            EngineNumber = "EN-HON-002",
                            FuelType = "Diesel",
                            ModelId = 3,
                            RegistrationNo = "XYZ-5678",
                            YearOfManufacture = 2018
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            ChasyNumber = "CH-TES-003",
                            EngineCapacity = "0cc",
                            EngineNumber = "EN-TES-003",
                            FuelType = "Electric",
                            ModelId = 5,
                            RegistrationNo = "TES-9001",
                            YearOfManufacture = 2020
                        });
                });

            modelBuilder.Entity("CarRentalAPI.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            ModelName = "Corolla"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            ModelName = "Camry"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            ModelName = "Civic"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            ModelName = "Accord"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            ModelName = "Model S"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 3,
                            ModelName = "Model X"
                        });
                });

            modelBuilder.Entity("CarRentalAPI.Models.Car", b =>
                {
                    b.HasOne("CarRentalAPI.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalAPI.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CarRentalAPI.Models.Model", b =>
                {
                    b.HasOne("CarRentalAPI.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("CarRentalAPI.Models.Brand", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
